import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const faqs = [
  {
    q: "What is a booking policy generator and how does it work?",
    a: "A booking policy generator is an online tool that creates a professional, customizable booking and cancellation policy for your service business. Simply enter your business details, set your cancellation window, fees, and refund rules, and the tool generates a ready-to-use policy you can copy to your website or booking platform.",
  },
  {
    q: "Can I use this cancellation policy generator for any type of business?",
    a: "Yes! Our cancellation policy generator supports a wide range of service industries including salons, spas, clinics, fitness studios, consulting firms, photography, and more. You can customize every detail to match your specific business needs.",
  },
  {
    q: "Is the booking policy template free to use?",
    a: "Absolutely. The booking policy template generated by this tool is 100% free. You can generate, copy, and use the policy on your website, booking page, or client communications without any cost.",
  },
  {
    q: "How do I add the cancellation policy template to my booking page?",
    a: "After generating your cancellation policy template, click the 'Copy to clipboard' button. Then paste it directly into your website's policy page, booking confirmation emails, or terms & conditions section. If you use Booknatic as your booking platform, you can add it directly in your settings.",
  },
];

const FAQSection = () => (
  <section className="py-16">
    <div className="container mx-auto px-4 max-w-3xl">
      <h2 className="text-2xl md:text-3xl font-bold text-foreground text-center mb-12">
        Frequently Asked Questions
      </h2>
      <Accordion type="single" collapsible className="space-y-3">
        {faqs.map((f, i) => (
          <AccordionItem key={i} value={`faq-${i}`} className="border border-border rounded-xl px-5 bg-card">
            <AccordionTrigger className="text-left font-semibold text-foreground hover:no-underline">
              {f.q}
            </AccordionTrigger>
            <AccordionContent className="text-muted-foreground leading-relaxed">
              {f.a}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  </section>
);

export default FAQSection;
